### ISSUE TITLE
Changing the gametype to something that does not contain 'ddracenet' or 'ddnet' will break rcon with ddnet client

### ISSUE THREAD

**Issue by abck** [abck/teeworlds#1]
Changing the gametype to something that does not contain 'ddracenet' or 'ddnet' will break rcon with ddnet client

https://github.com/abck/teeworlds/blob/DDRace64/src/engine/shared/serverbrowser.cpp#L16
https://github.com/abck/teeworlds/blob/DDRace64/src/engine/client/client.cpp#L449

**Comment by jxsl13** [comment]
what happens if you always return true instead of checking the gametype
